/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as OrgIdRouteImport } from './routes/$orgId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as ProjectsProjectSlugRouteImport } from './routes/projects.$projectSlug'
import { Route as IssuesIssueIdentifierRouteImport } from './routes/issues.$issueIdentifier'
import { Route as OrgIdTeamsRouteImport } from './routes/$orgId.teams'
import { Route as OrgIdSettingsRouteImport } from './routes/$orgId.settings'
import { Route as OrgIdProjectsRouteImport } from './routes/$orgId.projects'
import { Route as OrgIdMembersRouteImport } from './routes/$orgId.members'
import { Route as OrgIdIssuesRouteImport } from './routes/$orgId.issues'
import { Route as OrgIdInboxRouteImport } from './routes/$orgId.inbox'
import { Route as OrgIdIssuesIssueIdentifierRouteImport } from './routes/$orgId.issues.$issueIdentifier'
import { Route as OrgIdTeamTeamIdAllRouteImport } from './routes/$orgId.team.$teamId.all'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdRoute = OrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesRoute,
} as any)
const ProjectsProjectSlugRoute = ProjectsProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => ProjectsRoute,
} as any)
const IssuesIssueIdentifierRoute = IssuesIssueIdentifierRouteImport.update({
  id: '/$issueIdentifier',
  path: '/$issueIdentifier',
  getParentRoute: () => IssuesRoute,
} as any)
const OrgIdTeamsRoute = OrgIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => OrgIdRoute,
} as any)
const OrgIdSettingsRoute = OrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgIdRoute,
} as any)
const OrgIdProjectsRoute = OrgIdProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OrgIdRoute,
} as any)
const OrgIdMembersRoute = OrgIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgIdRoute,
} as any)
const OrgIdIssuesRoute = OrgIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OrgIdRoute,
} as any)
const OrgIdInboxRoute = OrgIdInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => OrgIdRoute,
} as any)
const OrgIdIssuesIssueIdentifierRoute =
  OrgIdIssuesIssueIdentifierRouteImport.update({
    id: '/$issueIdentifier',
    path: '/$issueIdentifier',
    getParentRoute: () => OrgIdIssuesRoute,
  } as any)
const OrgIdTeamTeamIdAllRoute = OrgIdTeamTeamIdAllRouteImport.update({
  id: '/team/$teamId/all',
  path: '/team/$teamId/all',
  getParentRoute: () => OrgIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdRouteWithChildren
  '/inbox': typeof InboxRoute
  '/issues': typeof IssuesRouteWithChildren
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/$orgId/inbox': typeof OrgIdInboxRoute
  '/$orgId/issues': typeof OrgIdIssuesRouteWithChildren
  '/$orgId/members': typeof OrgIdMembersRoute
  '/$orgId/projects': typeof OrgIdProjectsRoute
  '/$orgId/settings': typeof OrgIdSettingsRoute
  '/$orgId/teams': typeof OrgIdTeamsRoute
  '/issues/$issueIdentifier': typeof IssuesIssueIdentifierRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$orgId/issues/$issueIdentifier': typeof OrgIdIssuesIssueIdentifierRoute
  '/$orgId/team/$teamId/all': typeof OrgIdTeamTeamIdAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdRouteWithChildren
  '/inbox': typeof InboxRoute
  '/mcp': typeof McpRoute
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/$orgId/inbox': typeof OrgIdInboxRoute
  '/$orgId/issues': typeof OrgIdIssuesRouteWithChildren
  '/$orgId/members': typeof OrgIdMembersRoute
  '/$orgId/projects': typeof OrgIdProjectsRoute
  '/$orgId/settings': typeof OrgIdSettingsRoute
  '/$orgId/teams': typeof OrgIdTeamsRoute
  '/issues/$issueIdentifier': typeof IssuesIssueIdentifierRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/$orgId/issues/$issueIdentifier': typeof OrgIdIssuesIssueIdentifierRoute
  '/$orgId/team/$teamId/all': typeof OrgIdTeamTeamIdAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdRouteWithChildren
  '/inbox': typeof InboxRoute
  '/issues': typeof IssuesRouteWithChildren
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/$orgId/inbox': typeof OrgIdInboxRoute
  '/$orgId/issues': typeof OrgIdIssuesRouteWithChildren
  '/$orgId/members': typeof OrgIdMembersRoute
  '/$orgId/projects': typeof OrgIdProjectsRoute
  '/$orgId/settings': typeof OrgIdSettingsRoute
  '/$orgId/teams': typeof OrgIdTeamsRoute
  '/issues/$issueIdentifier': typeof IssuesIssueIdentifierRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$orgId/issues/$issueIdentifier': typeof OrgIdIssuesIssueIdentifierRoute
  '/$orgId/team/$teamId/all': typeof OrgIdTeamTeamIdAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgId'
    | '/inbox'
    | '/issues'
    | '/mcp'
    | '/projects'
    | '/pulse'
    | '/settings'
    | '/$orgId/inbox'
    | '/$orgId/issues'
    | '/$orgId/members'
    | '/$orgId/projects'
    | '/$orgId/settings'
    | '/$orgId/teams'
    | '/issues/$issueIdentifier'
    | '/projects/$projectSlug'
    | '/issues/'
    | '/projects/'
    | '/$orgId/issues/$issueIdentifier'
    | '/$orgId/team/$teamId/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgId'
    | '/inbox'
    | '/mcp'
    | '/pulse'
    | '/settings'
    | '/$orgId/inbox'
    | '/$orgId/issues'
    | '/$orgId/members'
    | '/$orgId/projects'
    | '/$orgId/settings'
    | '/$orgId/teams'
    | '/issues/$issueIdentifier'
    | '/projects/$projectSlug'
    | '/issues'
    | '/projects'
    | '/$orgId/issues/$issueIdentifier'
    | '/$orgId/team/$teamId/all'
  id:
    | '__root__'
    | '/'
    | '/$orgId'
    | '/inbox'
    | '/issues'
    | '/mcp'
    | '/projects'
    | '/pulse'
    | '/settings'
    | '/$orgId/inbox'
    | '/$orgId/issues'
    | '/$orgId/members'
    | '/$orgId/projects'
    | '/$orgId/settings'
    | '/$orgId/teams'
    | '/issues/$issueIdentifier'
    | '/projects/$projectSlug'
    | '/issues/'
    | '/projects/'
    | '/$orgId/issues/$issueIdentifier'
    | '/$orgId/team/$teamId/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgIdRoute: typeof OrgIdRouteWithChildren
  InboxRoute: typeof InboxRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  McpRoute: typeof McpRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PulseRoute: typeof PulseRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgId': {
      id: '/$orgId'
      path: '/$orgId'
      fullPath: '/$orgId'
      preLoaderRoute: typeof OrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/issues/$issueIdentifier': {
      id: '/issues/$issueIdentifier'
      path: '/$issueIdentifier'
      fullPath: '/issues/$issueIdentifier'
      preLoaderRoute: typeof IssuesIssueIdentifierRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/$orgId/teams': {
      id: '/$orgId/teams'
      path: '/teams'
      fullPath: '/$orgId/teams'
      preLoaderRoute: typeof OrgIdTeamsRouteImport
      parentRoute: typeof OrgIdRoute
    }
    '/$orgId/settings': {
      id: '/$orgId/settings'
      path: '/settings'
      fullPath: '/$orgId/settings'
      preLoaderRoute: typeof OrgIdSettingsRouteImport
      parentRoute: typeof OrgIdRoute
    }
    '/$orgId/projects': {
      id: '/$orgId/projects'
      path: '/projects'
      fullPath: '/$orgId/projects'
      preLoaderRoute: typeof OrgIdProjectsRouteImport
      parentRoute: typeof OrgIdRoute
    }
    '/$orgId/members': {
      id: '/$orgId/members'
      path: '/members'
      fullPath: '/$orgId/members'
      preLoaderRoute: typeof OrgIdMembersRouteImport
      parentRoute: typeof OrgIdRoute
    }
    '/$orgId/issues': {
      id: '/$orgId/issues'
      path: '/issues'
      fullPath: '/$orgId/issues'
      preLoaderRoute: typeof OrgIdIssuesRouteImport
      parentRoute: typeof OrgIdRoute
    }
    '/$orgId/inbox': {
      id: '/$orgId/inbox'
      path: '/inbox'
      fullPath: '/$orgId/inbox'
      preLoaderRoute: typeof OrgIdInboxRouteImport
      parentRoute: typeof OrgIdRoute
    }
    '/$orgId/issues/$issueIdentifier': {
      id: '/$orgId/issues/$issueIdentifier'
      path: '/$issueIdentifier'
      fullPath: '/$orgId/issues/$issueIdentifier'
      preLoaderRoute: typeof OrgIdIssuesIssueIdentifierRouteImport
      parentRoute: typeof OrgIdIssuesRoute
    }
    '/$orgId/team/$teamId/all': {
      id: '/$orgId/team/$teamId/all'
      path: '/team/$teamId/all'
      fullPath: '/$orgId/team/$teamId/all'
      preLoaderRoute: typeof OrgIdTeamTeamIdAllRouteImport
      parentRoute: typeof OrgIdRoute
    }
  }
}

interface OrgIdIssuesRouteChildren {
  OrgIdIssuesIssueIdentifierRoute: typeof OrgIdIssuesIssueIdentifierRoute
}

const OrgIdIssuesRouteChildren: OrgIdIssuesRouteChildren = {
  OrgIdIssuesIssueIdentifierRoute: OrgIdIssuesIssueIdentifierRoute,
}

const OrgIdIssuesRouteWithChildren = OrgIdIssuesRoute._addFileChildren(
  OrgIdIssuesRouteChildren,
)

interface OrgIdRouteChildren {
  OrgIdInboxRoute: typeof OrgIdInboxRoute
  OrgIdIssuesRoute: typeof OrgIdIssuesRouteWithChildren
  OrgIdMembersRoute: typeof OrgIdMembersRoute
  OrgIdProjectsRoute: typeof OrgIdProjectsRoute
  OrgIdSettingsRoute: typeof OrgIdSettingsRoute
  OrgIdTeamsRoute: typeof OrgIdTeamsRoute
  OrgIdTeamTeamIdAllRoute: typeof OrgIdTeamTeamIdAllRoute
}

const OrgIdRouteChildren: OrgIdRouteChildren = {
  OrgIdInboxRoute: OrgIdInboxRoute,
  OrgIdIssuesRoute: OrgIdIssuesRouteWithChildren,
  OrgIdMembersRoute: OrgIdMembersRoute,
  OrgIdProjectsRoute: OrgIdProjectsRoute,
  OrgIdSettingsRoute: OrgIdSettingsRoute,
  OrgIdTeamsRoute: OrgIdTeamsRoute,
  OrgIdTeamTeamIdAllRoute: OrgIdTeamTeamIdAllRoute,
}

const OrgIdRouteWithChildren = OrgIdRoute._addFileChildren(OrgIdRouteChildren)

interface IssuesRouteChildren {
  IssuesIssueIdentifierRoute: typeof IssuesIssueIdentifierRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIssueIdentifierRoute: IssuesIssueIdentifierRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectSlugRoute: typeof ProjectsProjectSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectSlugRoute: ProjectsProjectSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgIdRoute: OrgIdRouteWithChildren,
  InboxRoute: InboxRoute,
  IssuesRoute: IssuesRouteWithChildren,
  McpRoute: McpRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PulseRoute: PulseRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
